name: Docker Publish

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ 'README.md' ]
    # También puedes agregar tags para publicar versiones específicas
    tags: [ 'v*' ]
  # Opcionalmente, permitir ejecución manual desde la interfaz de GitHub
  workflow_dispatch:
env:
  # Establecer repositorio de Docker Hub como predeterminado
  REGISTRY: docker.io
  # github.repository como <cuenta>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Agregar esta línea si quieres que corra en tus runners personalizados
    # runs-on: [self-hosted, ubuntu-latest]
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Buildx para compilación multi-plataforma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extraer metadata para etiquetas Docker
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest


      # Construir y publicar la imagen
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
